on:
  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - public/**
      - cypress/**
      - config/**
      - github/**
      - package.json

jobs:
  electron:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: /github/home/.cache/Cypress
          key: cypress-binary-1${{ hashFiles('/github/home/.cache/Cypress') }}

      - name: Install
        run: |
          npm run setup
          npx cypress install

      - name: Electron
        run: npm run test:electron
