on:
  pull_request:
    branches: ["main"]

jobs:
  general:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome89-ff86

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - name: Install
        run: |
          npm run setup

      - name: Lint
        run: |
          npm run lint
