on:
  push:
    branches: ["*"]

jobs:
  firefox:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome89-ff86

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - name: Install
        run: |
          npm run setup
          npx cypress install

      - name: firefox
        run: npm run test:firefox

  edge:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-edge
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Cypress\Cache
          key: cypress-binary-1${{ hashFiles('C:\Users\runneradmin\AppData\Local\Cypress\Cache') }}

      - name: Install
        run: |
          npm run setup
          npx cypress install

      - name: Edge
        run: npm run test:edge

  chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: /github/home/.cache/Cypress
          key: cypress-binary-1${{ hashFiles('/github/home/.cache/Cypress') }}

      - name: Install
        run: |
          npm run setup
          npx cypress install

      - name: Chrome
        run: npm run test:chrome
